imports:
    - { resource: twig.yml }
    - { resource: manager.yml }
    - { resource: listener.yml }

parameters:
     social_template.registrationconfirm.listener: AppBundle\EventListener\SuccessAuthentificationListener

services:
    social_template.registration_complet:
        class: "%social_template.registrationconfirm.listener%"
        arguments:
            - "@router"
            - "@translator.default"
        tags:
            - { name: kernel.event_subscriber }

    app.form.profile:
        class: AppBundle\Form\ProfileType
        tags:
            - { name: form.type, alias: app_user_profile }